import type { ThemeSectionDef } from '../../../_types'

export const accountDashboardSection: ThemeSectionDef = {
  id: 'dashboard',
  label: 'Tableau de bord',
  description: 'Contenu principal de l\'espace compte avec onglets',
  fields: [
    {
      key: 'separatorTabs',
      label: 'Configuration des onglets',
      type: 'separator',
    },
    {
      key: 'defaultTab',
      label: 'Onglet par défaut',
      type: 'select',
      defaultValue: 'profile',
      options: [
        { value: 'profile', label: 'Mon profil' },
        { value: 'orders', label: 'Mes commandes' },
        { value: 'addresses', label: 'Mes adresses' },
      ],
    },
    {
      key: 'separatorProfileTab',
      label: 'Onglet Profil',
      type: 'separator',
    },
    {
      key: 'showProfileTab',
      label: 'Afficher l\'onglet Profil',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'profileTabLabel',
      label: 'Libellé de l\'onglet',
      type: 'text',
      defaultValue: 'Mon profil',
      showWhen: { field: 'showProfileTab', value: true },
    },
    {
      key: 'showLoyaltyPoints',
      label: 'Afficher les points fidélité',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'showProfileTab', value: true },
    },
    {
      key: 'showChangePassword',
      label: 'Permettre le changement de mot de passe',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'showProfileTab', value: true },
    },
    {
      key: 'separatorOrdersTab',
      label: 'Onglet Commandes',
      type: 'separator',
    },
    {
      key: 'showOrdersTab',
      label: 'Afficher l\'onglet Commandes',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'ordersTabLabel',
      label: 'Libellé de l\'onglet',
      type: 'text',
      defaultValue: 'Mes commandes',
      showWhen: { field: 'showOrdersTab', value: true },
    },
    {
      key: 'ordersPerPage',
      label: 'Commandes par page',
      type: 'number',
      defaultValue: 10,
      min: 5,
      max: 50,
      showWhen: { field: 'showOrdersTab', value: true },
    },
    {
      key: 'showOrderDetails',
      label: 'Afficher les détails des commandes',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'showOrdersTab', value: true },
    },
    {
      key: 'separatorAddressesTab',
      label: 'Onglet Adresses',
      type: 'separator',
    },
    {
      key: 'showAddressesTab',
      label: 'Afficher l\'onglet Adresses',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'addressesTabLabel',
      label: 'Libellé de l\'onglet',
      type: 'text',
      defaultValue: 'Mes adresses',
      showWhen: { field: 'showAddressesTab', value: true },
    },
    {
      key: 'maxAddresses',
      label: 'Nombre maximum d\'adresses',
      type: 'number',
      defaultValue: 5,
      min: 1,
      max: 20,
      description: 'Limite le nombre d\'adresses que le client peut enregistrer',
      showWhen: { field: 'showAddressesTab', value: true },
    },
    {
      key: 'separatorSidebar',
      label: 'Barre latérale',
      type: 'separator',
    },
    {
      key: 'showAvatar',
      label: 'Afficher l\'avatar',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'showLogoutBtn',
      label: 'Bouton déconnexion',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'sidebarPosition',
      label: 'Position de la barre latérale',
      type: 'select',
      defaultValue: 'left',
      options: [
        { value: 'left', label: 'À gauche' },
        { value: 'right', label: 'À droite' },
        { value: 'top', label: 'En haut (tabs horizontaux)' },
      ],
    },
  ],
}
