import type { ThemeSectionDef } from '../../../_types'

export const heroSection: ThemeSectionDef = {
  id: 'hero',
  label: 'Hero / Bannière',
  description: 'La section principale en haut de la page d\'accueil',
  fields: [
    {
      key: 'enabled',
      label: 'Activer cette section',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'bgType',
      label: 'Type d\'arrière-plan',
      type: 'select',
      defaultValue: 'image',
      options: [
        { value: 'image', label: 'Image' },
        { value: 'video', label: 'Vidéo' },
        { value: 'gradient', label: 'Dégradé de couleurs' },
      ],
      description: 'Choisissez le type de fond pour la bannière',
    },
    {
      key: 'bgImage',
      label: 'Image d\'arrière-plan',
      type: 'image',
      description: 'Uploadez une image personnalisée (sinon l\'image de couverture du restaurant sera utilisée)',
      showWhen: { field: 'bgType', value: 'image' },
    },
    {
      key: 'videoUrl',
      label: 'URL de la vidéo',
      type: 'text',
      placeholder: 'https://exemple.com/video.mp4',
      description: 'Lien direct vers un fichier vidéo (MP4 recommandé)',
      showWhen: { field: 'bgType', value: 'video' },
    },
    {
      key: 'gradientFrom',
      label: 'Couleur de départ du dégradé',
      type: 'color',
      description: 'Couleur de départ (utilisée si type = dégradé)',
      showWhen: { field: 'bgType', value: 'gradient' },
    },
    {
      key: 'gradientTo',
      label: 'Couleur d\'arrivée du dégradé',
      type: 'color',
      description: 'Couleur d\'arrivée (utilisée si type = dégradé)',
      showWhen: { field: 'bgType', value: 'gradient' },
    },
    {
      key: 'overlayOpacity',
      label: 'Opacité de l\'overlay',
      type: 'slider',
      defaultValue: 50,
      min: 0,
      max: 100,
      step: 5,
      description: 'Assombrir l\'arrière-plan pour améliorer la lisibilité',
    },
    {
      key: 'overlayBlur',
      label: 'Flou de l\'arrière-plan',
      type: 'slider',
      defaultValue: 0,
      min: 0,
      max: 20,
      step: 1,
      description: 'Appliquer un effet de flou sur l\'arrière-plan (en pixels)',
    },
    {
      key: 'minHeight',
      label: 'Hauteur minimale',
      type: 'select',
      defaultValue: '70vh',
      options: [
        { value: '50vh', label: 'Petite (50%)' },
        { value: '70vh', label: 'Moyenne (70%)' },
        { value: '85vh', label: 'Grande (85%)' },
        { value: '100vh', label: 'Plein écran (100%)' },
      ],
    },
    {
      key: 'showLogo',
      label: 'Afficher le logo',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'title',
      label: 'Titre',
      type: 'text',
      placeholder: 'Nom du restaurant par défaut',
      description: 'Laissez vide pour utiliser le nom du restaurant',
    },
    {
      key: 'subtitle',
      label: 'Sous-titre',
      type: 'textarea',
      placeholder: 'Description courte par défaut',
      description: 'Laissez vide pour utiliser la description courte du restaurant',
    },
    {
      key: 'titleAlign',
      label: 'Alignement du texte',
      type: 'select',
      defaultValue: 'center',
      options: [
        { value: 'left', label: 'Gauche' },
        { value: 'center', label: 'Centré' },
      ],
    },
    {
      key: 'ctaText',
      label: 'Texte du bouton principal',
      type: 'text',
      placeholder: 'Voir le menu',
      defaultValue: 'Voir le menu',
    },
    {
      key: 'ctaIcon',
      label: 'Icone du bouton principal',
      type: 'icon',
      description: 'Icone affichée dans le bouton principal',
    },
    {
      key: 'showSecondaryBtn',
      label: 'Afficher un second bouton',
      type: 'switch',
      defaultValue: false,
    },
    {
      key: 'secondaryBtnText',
      label: 'Texte du second bouton',
      type: 'text',
      placeholder: 'Nous contacter',
      defaultValue: 'Nous contacter',
      showWhen: { field: 'showSecondaryBtn', value: true },
    },
    {
      key: 'secondaryBtnIcon',
      label: 'Icone du second bouton',
      type: 'icon',
      description: 'Icone affichée dans le second bouton',
      showWhen: { field: 'showSecondaryBtn', value: true },
    },
    {
      key: 'secondaryBtnLink',
      label: 'Lien du second bouton',
      type: 'select',
      defaultValue: 'contact',
      options: [
        { value: 'contact', label: 'Page contact' },
        { value: 'menu', label: 'Page menu' },
      ],
      showWhen: { field: 'showSecondaryBtn', value: true },
    },
    {
      key: 'showBadge',
      label: 'Badge "Ouvert maintenant"',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'showCuisineTypes',
      label: 'Afficher les types de cuisine',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'showDeliveryBadge',
      label: 'Badge livraison',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'showPrepTimeBadge',
      label: 'Badge temps de préparation',
      type: 'switch',
      defaultValue: true,
    },
  ],
}
