import type { ThemeSectionDef } from '../../../_types'

export const statsSection: ThemeSectionDef = {
  id: 'stats',
  label: 'Chiffres clés',
  description: 'Section de statistiques avec compteurs (ex: années d\'expérience, plats, clients...)',
  fields: [
    {
      key: 'enabled',
      label: 'Activer cette section',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'bgStyle',
      label: 'Style de fond',
      type: 'select',
      defaultValue: 'accent',
      options: [
        { value: 'light', label: 'Clair' },
        { value: 'accent', label: 'Accent léger' },
        { value: 'primary', label: 'Couleur principale' },
        { value: 'dark', label: 'Sombre' },
      ],
    },
    {
      key: 'showSeparators',
      label: 'Afficher les séparateurs',
      type: 'switch',
      defaultValue: true,
      description: 'Lignes verticales entre les chiffres',
    },
    {
      key: 'iconLayout',
      label: 'Position des icones',
      type: 'select',
      defaultValue: 'top',
      options: [
        { value: 'top', label: 'Au-dessus du chiffre' },
        { value: 'left', label: 'À gauche du chiffre' },
      ],
      description: 'Disposition des icones par rapport aux chiffres',
    },
    {
      key: '_sep0',
      label: 'Chiffre 1',
      type: 'separator',
    },
    {
      key: 'stat0Enabled',
      label: 'Activer',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'stat0Mode',
      label: 'Source de la valeur',
      type: 'select',
      defaultValue: 'custom',
      options: [
        { value: 'custom', label: 'Valeur personnalisée' },
        { value: 'dynamic', label: 'Valeur dynamique (données réelles)' },
      ],
      showWhen: { field: 'stat0Enabled', value: true },
    },
    {
      key: 'stat0Value',
      label: 'Valeur affichée',
      type: 'text',
      placeholder: '10+',
      defaultValue: '10+',
      showWhen: { field: 'stat0Mode', value: 'custom' },
    },
    {
      key: 'stat0Source',
      label: 'Donnée dynamique',
      type: 'select',
      defaultValue: 'totalProducts',
      options: [
        { value: 'totalProducts', label: 'Nombre de plats au menu' },
        { value: 'totalCategories', label: 'Nombre de catégories' },
        { value: 'cuisineTypes', label: 'Nombre de types de cuisine' },
      ],
      showWhen: { field: 'stat0Mode', value: 'dynamic' },
    },
    {
      key: 'stat0Suffix',
      label: 'Suffixe',
      type: 'text',
      placeholder: '+',
      description: 'Ajouté après la valeur dynamique (ex: +, plats, etc.)',
      showWhen: { field: 'stat0Mode', value: 'dynamic' },
    },
    {
      key: 'stat0Icon',
      label: 'Icone',
      type: 'icon',
      description: 'Icone affichée au-dessus du chiffre',
      showWhen: { field: 'stat0Enabled', value: true },
    },
    {
      key: 'stat0Label',
      label: 'Libellé',
      type: 'text',
      placeholder: 'Années d\'expérience',
      defaultValue: 'Années d\'expérience',
      showWhen: { field: 'stat0Enabled', value: true },
    },
    {
      key: '_sep1',
      label: 'Chiffre 2',
      type: 'separator',
    },
    {
      key: 'stat1Enabled',
      label: 'Activer',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'stat1Mode',
      label: 'Source de la valeur',
      type: 'select',
      defaultValue: 'dynamic',
      options: [
        { value: 'custom', label: 'Valeur personnalisée' },
        { value: 'dynamic', label: 'Valeur dynamique (données réelles)' },
      ],
      showWhen: { field: 'stat1Enabled', value: true },
    },
    {
      key: 'stat1Value',
      label: 'Valeur affichée',
      type: 'text',
      placeholder: '50+',
      defaultValue: '50+',
      showWhen: { field: 'stat1Mode', value: 'custom' },
    },
    {
      key: 'stat1Source',
      label: 'Donnée dynamique',
      type: 'select',
      defaultValue: 'totalProducts',
      options: [
        { value: 'totalProducts', label: 'Nombre de plats au menu' },
        { value: 'totalCategories', label: 'Nombre de catégories' },
        { value: 'cuisineTypes', label: 'Nombre de types de cuisine' },
      ],
      showWhen: { field: 'stat1Mode', value: 'dynamic' },
    },
    {
      key: 'stat1Suffix',
      label: 'Suffixe',
      type: 'text',
      placeholder: '+',
      description: 'Ajouté après la valeur dynamique (ex: +, plats, etc.)',
      showWhen: { field: 'stat1Mode', value: 'dynamic' },
    },
    {
      key: 'stat1Icon',
      label: 'Icone',
      type: 'icon',
      description: 'Icone affichée au-dessus du chiffre',
      showWhen: { field: 'stat1Enabled', value: true },
    },
    {
      key: 'stat1Label',
      label: 'Libellé',
      type: 'text',
      placeholder: 'Plats au menu',
      defaultValue: 'Plats au menu',
      showWhen: { field: 'stat1Enabled', value: true },
    },
    {
      key: '_sep2',
      label: 'Chiffre 3',
      type: 'separator',
    },
    {
      key: 'stat2Enabled',
      label: 'Activer',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'stat2Mode',
      label: 'Source de la valeur',
      type: 'select',
      defaultValue: 'custom',
      options: [
        { value: 'custom', label: 'Valeur personnalisée' },
        { value: 'dynamic', label: 'Valeur dynamique (données réelles)' },
      ],
      showWhen: { field: 'stat2Enabled', value: true },
    },
    {
      key: 'stat2Value',
      label: 'Valeur affichée',
      type: 'text',
      placeholder: '15+',
      defaultValue: '15+',
      showWhen: { field: 'stat2Mode', value: 'custom' },
    },
    {
      key: 'stat2Source',
      label: 'Donnée dynamique',
      type: 'select',
      defaultValue: 'totalProducts',
      options: [
        { value: 'totalProducts', label: 'Nombre de plats au menu' },
        { value: 'totalCategories', label: 'Nombre de catégories' },
        { value: 'cuisineTypes', label: 'Nombre de types de cuisine' },
      ],
      showWhen: { field: 'stat2Mode', value: 'dynamic' },
    },
    {
      key: 'stat2Suffix',
      label: 'Suffixe',
      type: 'text',
      placeholder: '+',
      description: 'Ajouté après la valeur dynamique (ex: +, plats, etc.)',
      showWhen: { field: 'stat2Mode', value: 'dynamic' },
    },
    {
      key: 'stat2Icon',
      label: 'Icone',
      type: 'icon',
      description: 'Icone affichée au-dessus du chiffre',
      showWhen: { field: 'stat2Enabled', value: true },
    },
    {
      key: 'stat2Label',
      label: 'Libellé',
      type: 'text',
      placeholder: 'Services / jour',
      defaultValue: 'Services / jour',
      showWhen: { field: 'stat2Enabled', value: true },
    },
    {
      key: '_sep3',
      label: 'Chiffre 4',
      type: 'separator',
    },
    {
      key: 'stat3Enabled',
      label: 'Activer',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'stat3Mode',
      label: 'Source de la valeur',
      type: 'select',
      defaultValue: 'custom',
      options: [
        { value: 'custom', label: 'Valeur personnalisée' },
        { value: 'dynamic', label: 'Valeur dynamique (données réelles)' },
      ],
      showWhen: { field: 'stat3Enabled', value: true },
    },
    {
      key: 'stat3Value',
      label: 'Valeur affichée',
      type: 'text',
      placeholder: '1000+',
      defaultValue: '1000+',
      showWhen: { field: 'stat3Mode', value: 'custom' },
    },
    {
      key: 'stat3Source',
      label: 'Donnée dynamique',
      type: 'select',
      defaultValue: 'totalProducts',
      options: [
        { value: 'totalProducts', label: 'Nombre de plats au menu' },
        { value: 'totalCategories', label: 'Nombre de catégories' },
        { value: 'cuisineTypes', label: 'Nombre de types de cuisine' },
      ],
      showWhen: { field: 'stat3Mode', value: 'dynamic' },
    },
    {
      key: 'stat3Suffix',
      label: 'Suffixe',
      type: 'text',
      placeholder: '+',
      description: 'Ajouté après la valeur dynamique (ex: +, plats, etc.)',
      showWhen: { field: 'stat3Mode', value: 'dynamic' },
    },
    {
      key: 'stat3Icon',
      label: 'Icone',
      type: 'icon',
      description: 'Icone affichée au-dessus du chiffre',
      showWhen: { field: 'stat3Enabled', value: true },
    },
    {
      key: 'stat3Label',
      label: 'Libellé',
      type: 'text',
      placeholder: 'Clients satisfaits',
      defaultValue: 'Clients satisfaits',
      showWhen: { field: 'stat3Enabled', value: true },
    },
  ],
}
