import type { ThemeSectionDef } from '../../../_types'

export const testimonialsSection: ThemeSectionDef = {
  id: 'testimonials',
  label: 'Témoignages clients',
  description: 'Témoignages personnalisés de vos clients',
  fields: [
    {
      key: 'enabled',
      label: 'Activer cette section',
      type: 'switch',
      defaultValue: false,
      description: 'Désactivée par défaut, activez pour afficher les témoignages',
    },
    {
      key: 'title',
      label: 'Titre',
      type: 'text',
      placeholder: 'Ce que disent nos clients',
      defaultValue: 'Ce que disent nos clients',
    },
    {
      key: 'subtitle',
      label: 'Sous-titre',
      type: 'text',
      placeholder: 'Leurs avis comptent pour nous',
    },
    {
      key: 'layout',
      label: 'Disposition',
      type: 'select',
      defaultValue: 'grid',
      options: [
        { value: 'grid', label: 'Grille de cartes' },
        { value: 'carousel', label: 'Carrousel (défilement)' },
      ],
    },
    {
      key: 'carouselVisible',
      label: 'Carrousel : témoignages visibles',
      type: 'slider',
      defaultValue: 3,
      min: 1,
      max: 4,
      step: 1,
      description: 'Nombre de témoignages affichés simultanément',
      showWhen: { field: 'layout', value: 'carousel' },
    },
    {
      key: 'carouselScroll',
      label: 'Carrousel : défilement par',
      type: 'slider',
      defaultValue: 1,
      min: 1,
      max: 3,
      step: 1,
      description: 'Nombre de témoignages défilés à chaque clic',
      showWhen: { field: 'layout', value: 'carousel' },
    },
    {
      key: 'carouselAutoplay',
      label: 'Carrousel : défilement automatique',
      type: 'switch',
      defaultValue: false,
      showWhen: { field: 'layout', value: 'carousel' },
    },
    {
      key: 'carouselAutoplayDelay',
      label: 'Carrousel : délai entre défilements (secondes)',
      type: 'slider',
      defaultValue: 5,
      min: 2,
      max: 10,
      step: 1,
      showWhen: { field: 'carouselAutoplay', value: true },
    },
    {
      key: 'quoteIcon',
      label: 'Icone de citation',
      type: 'icon',
      description: 'Icone affichée en haut de chaque carte de témoignage (par défaut : guillemets)',
    },
    {
      key: 'testimonials',
      label: 'Témoignages',
      type: 'testimonials',
      description: 'Ajoutez autant de témoignages que vous souhaitez. Si aucun n\'est ajouté, des exemples seront affichés.',
    },
  ],
}
