import type { ThemeSectionDef } from '../../../_types'

export const twoColumnsSection: ThemeSectionDef = {
  id: 'twoColumns',
  label: 'Présentation',
  description: 'Section image + texte avec badge et boutons d\'action',
  fields: [
    {
      key: 'enabled',
      label: 'Activer cette section',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'layout',
      label: 'Disposition',
      type: 'select',
      defaultValue: 'imageLeft',
      options: [
        { value: 'imageLeft', label: 'Image à gauche' },
        { value: 'imageRight', label: 'Image à droite' },
      ],
    },
    {
      key: 'bgStyle',
      label: 'Style de fond',
      type: 'select',
      defaultValue: 'light',
      options: [
        { value: 'light', label: 'Clair (couleur de fond)' },
        { value: 'accent', label: 'Accent léger' },
        { value: 'dark', label: 'Sombre' },
      ],
    },
    {
      key: 'showBadge',
      label: 'Afficher le badge',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'badge',
      label: 'Texte du badge',
      type: 'text',
      placeholder: 'Qui sommes-nous',
      defaultValue: 'Qui sommes-nous',
      showWhen: { field: 'showBadge', value: true },
    },
    {
      key: 'title',
      label: 'Titre',
      type: 'text',
      placeholder: 'Nom du restaurant par défaut',
      description: 'Laissez vide pour utiliser le nom du restaurant',
    },
    {
      key: 'text',
      label: 'Texte de présentation',
      type: 'textarea',
      placeholder: 'Décrivez votre restaurant, votre philosophie, vos valeurs...',
      description: 'Laissez vide pour utiliser la description du restaurant',
    },
    {
      key: 'image',
      label: 'Image principale',
      type: 'image',
      description: 'Image affichée à côté du texte (sinon l\'image de couverture sera utilisée)',
    },
    {
      key: 'imageHeight',
      label: 'Hauteur de l\'image',
      type: 'select',
      defaultValue: 'auto',
      options: [
        { value: 'auto', label: 'Automatique (ratio 4/5)' },
        { value: 'sm', label: 'Petite (300px)' },
        { value: 'md', label: 'Moyenne (400px)' },
        { value: 'lg', label: 'Grande (500px)' },
        { value: 'xl', label: 'Très grande (600px)' },
        { value: 'full', label: 'Pleine hauteur' },
      ],
    },
    {
      key: 'imageFit',
      label: 'Ajustement de l\'image',
      type: 'select',
      defaultValue: 'cover',
      options: [
        { value: 'cover', label: 'Couvrir (recadrage)' },
        { value: 'contain', label: 'Contenir (taille d\'origine)' },
        { value: 'fill', label: 'Étirer' },
      ],
    },
    {
      key: 'imageRounded',
      label: 'Arrondi de l\'image',
      type: 'select',
      defaultValue: '3xl',
      options: [
        { value: 'none', label: 'Aucun' },
        { value: 'xl', label: 'Léger' },
        { value: '2xl', label: 'Moyen' },
        { value: '3xl', label: 'Fort' },
      ],
    },
    {
      key: 'showSecondImage',
      label: 'Afficher une seconde image (ronde)',
      type: 'switch',
      defaultValue: false,
    },
    {
      key: 'secondImage',
      label: 'Seconde image',
      type: 'image',
      description: 'Petite image ronde superposée sur l\'image principale',
      showWhen: { field: 'showSecondImage', value: true },
    },
    {
      key: 'secondImageSize',
      label: 'Taille de la seconde image',
      type: 'select',
      defaultValue: 'md',
      options: [
        { value: 'sm', label: 'Petite' },
        { value: 'md', label: 'Moyenne' },
        { value: 'lg', label: 'Grande' },
      ],
      showWhen: { field: 'showSecondImage', value: true },
    },
    {
      key: 'secondImageAnimation',
      label: 'Animation de la seconde image',
      type: 'select',
      defaultValue: 'none',
      options: [
        { value: 'none', label: 'Aucune' },
        { value: 'bounce', label: 'Rebond' },
        { value: 'pulse', label: 'Pulsation' },
        { value: 'float', label: 'Flottement' },
      ],
      showWhen: { field: 'showSecondImage', value: true },
    },
    {
      key: 'showBtn',
      label: 'Afficher le bouton principal',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'btnText',
      label: 'Texte du bouton',
      type: 'text',
      placeholder: 'En savoir plus',
      defaultValue: 'En savoir plus',
      showWhen: { field: 'showBtn', value: true },
    },
    {
      key: 'btnIcon',
      label: 'Icone du bouton',
      type: 'icon',
      description: 'Icone affichée dans le bouton',
      showWhen: { field: 'showBtn', value: true },
    },
    {
      key: 'btnLink',
      label: 'Destination du bouton',
      type: 'select',
      defaultValue: 'contact',
      options: [
        { value: 'contact', label: 'Page contact' },
        { value: 'menu', label: 'Page menu' },
      ],
      showWhen: { field: 'showBtn', value: true },
    },
    {
      key: 'showArrowBtn',
      label: 'Afficher le bouton flèche',
      type: 'switch',
      defaultValue: true,
    },
  ],
}
