import type { ThemeSectionDef } from '../../../_types'

export const teamSection: ThemeSectionDef = {
  id: 'team',
  label: 'Équipe',
  description: 'Grille de cartes des membres de l\'équipe',
  fields: [
    {
      key: 'enabled',
      label: 'Activer la section',
      type: 'switch',
      defaultValue: false,
    },
    {
      key: 'title',
      label: 'Titre',
      type: 'text',
      placeholder: 'Notre équipe',
      defaultValue: 'Notre équipe',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'subtitle',
      label: 'Sous-titre',
      type: 'text',
      placeholder: 'L\'équipe dévouée derrière vos plats préférés',
      defaultValue: 'L\'équipe dévouée derrière vos plats préférés',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'member1Name',
      label: 'Nom membre 1',
      type: 'text',
      placeholder: 'Jean Dupont',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'member1Role',
      label: 'Rôle membre 1',
      type: 'text',
      placeholder: 'Chef cuisinier',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'member1Image',
      label: 'Photo membre 1',
      type: 'image',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'member2Name',
      label: 'Nom membre 2',
      type: 'text',
      placeholder: 'Marie Martin',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'member2Role',
      label: 'Rôle membre 2',
      type: 'text',
      placeholder: 'Sous-chef',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'member2Image',
      label: 'Photo membre 2',
      type: 'image',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'member3Name',
      label: 'Nom membre 3',
      type: 'text',
      placeholder: 'Pierre Bernard',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'member3Role',
      label: 'Rôle membre 3',
      type: 'text',
      placeholder: 'Pâtissier',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'member3Image',
      label: 'Photo membre 3',
      type: 'image',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'member4Name',
      label: 'Nom membre 4',
      type: 'text',
      placeholder: 'Sophie Leroy',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'member4Role',
      label: 'Rôle membre 4',
      type: 'text',
      placeholder: 'Responsable salle',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'member4Image',
      label: 'Photo membre 4',
      type: 'image',
      showWhen: { field: 'enabled', value: true },
    },
  ],
}
