import type { ThemeSectionDef } from '../../../_types'

export const timelineSection: ThemeSectionDef = {
  id: 'timeline',
  label: 'Chronologie',
  description: 'Timeline verticale avec années et descriptions',
  fields: [
    {
      key: 'enabled',
      label: 'Activer la section',
      type: 'switch',
      defaultValue: false,
    },
    {
      key: 'title',
      label: 'Titre',
      type: 'text',
      placeholder: 'Notre histoire',
      defaultValue: 'Notre histoire',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'subtitle',
      label: 'Sous-titre',
      type: 'text',
      placeholder: 'Des souvenirs chaleureux au fil des années',
      defaultValue: 'Des souvenirs chaleureux au fil des années',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'event1Year',
      label: 'Année 1',
      type: 'text',
      placeholder: '2018',
      defaultValue: '2018',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'event1Title',
      label: 'Titre événement 1',
      type: 'text',
      placeholder: 'Ouverture du restaurant',
      defaultValue: 'Ouverture du restaurant',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'event1Text',
      label: 'Description événement 1',
      type: 'textarea',
      placeholder: 'Le début de notre aventure culinaire...',
      defaultValue: 'Le début de notre aventure culinaire dans un petit local chaleureux.',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'event1Image',
      label: 'Image événement 1',
      type: 'image',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'event2Year',
      label: 'Année 2',
      type: 'text',
      placeholder: '2020',
      defaultValue: '2020',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'event2Title',
      label: 'Titre événement 2',
      type: 'text',
      placeholder: 'Agrandissement',
      defaultValue: 'Agrandissement',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'event2Text',
      label: 'Description événement 2',
      type: 'textarea',
      placeholder: 'Nous avons agrandi notre espace...',
      defaultValue: 'Nous avons agrandi notre espace pour accueillir encore plus de convives.',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'event2Image',
      label: 'Image événement 2',
      type: 'image',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'event3Year',
      label: 'Année 3',
      type: 'text',
      placeholder: '2022',
      defaultValue: '2022',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'event3Title',
      label: 'Titre événement 3',
      type: 'text',
      placeholder: 'Nouveau menu',
      defaultValue: 'Nouveau menu',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'event3Text',
      label: 'Description événement 3',
      type: 'textarea',
      placeholder: 'Lancement de notre nouveau menu signature...',
      defaultValue: 'Lancement de notre nouveau menu signature avec des produits locaux.',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'event3Image',
      label: 'Image événement 3',
      type: 'image',
      showWhen: { field: 'enabled', value: true },
    },
  ],
}
