import type { ThemeSectionDef } from '../../../_types'

export const customContentSection: ThemeSectionDef = {
  id: 'content',
  label: 'Contenu texte',
  description: 'Bloc de contenu texte principal de la page',
  fields: [
    {
      key: 'enabled',
      label: 'Activer cette section',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'separator_content',
      label: 'Contenu',
      type: 'separator',
      description: 'Le contenu principal de la section',
    },
    {
      key: 'contentSource',
      label: 'Source du contenu',
      type: 'select',
      defaultValue: 'page',
      options: [
        { value: 'page', label: 'Contenu de la page (onglet Général)' },
        { value: 'custom', label: 'Contenu personnalisé pour cette section' },
      ],
      description: 'Utilisez le contenu de la page ou écrivez un contenu spécifique à cette section',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'customContent',
      label: 'Contenu personnalisé',
      type: 'textarea',
      placeholder: 'Écrivez votre contenu ici...',
      description: 'Ce contenu sera affiché à la place du contenu de la page',
      showWhen: { field: 'contentSource', value: 'custom' },
    },
    {
      key: 'showTitle',
      label: 'Afficher un titre de section',
      type: 'switch',
      defaultValue: false,
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'title',
      label: 'Titre de la section',
      type: 'text',
      placeholder: 'Titre de la section',
      showWhen: { field: 'showTitle', value: true },
    },
    {
      key: 'separator_style',
      label: 'Style et mise en page',
      type: 'separator',
    },
    {
      key: 'maxWidth',
      label: 'Largeur maximale',
      type: 'select',
      defaultValue: 'lg',
      options: [
        { value: 'sm', label: 'Étroite (640px)' },
        { value: 'md', label: 'Moyenne (768px)' },
        { value: 'lg', label: 'Large (1024px)' },
        { value: 'full', label: 'Pleine largeur' },
      ],
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'textAlign',
      label: 'Alignement du texte',
      type: 'select',
      defaultValue: 'left',
      options: [
        { value: 'left', label: 'Gauche' },
        { value: 'center', label: 'Centré' },
      ],
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'fontSize',
      label: 'Taille du texte',
      type: 'select',
      defaultValue: 'base',
      options: [
        { value: 'sm', label: 'Petit' },
        { value: 'base', label: 'Normal' },
        { value: 'lg', label: 'Grand' },
      ],
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'textColor',
      label: 'Couleur du texte',
      type: 'color',
      description: 'Laissez vide pour utiliser la couleur par défaut du thème',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separator_background',
      label: 'Arrière-plan et espacement',
      type: 'separator',
    },
    {
      key: 'bgColor',
      label: 'Couleur de fond',
      type: 'color',
      description: 'Laissez vide pour un fond transparent',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'paddingY',
      label: 'Espacement vertical',
      type: 'select',
      defaultValue: 'md',
      options: [
        { value: 'sm', label: 'Petit' },
        { value: 'md', label: 'Moyen' },
        { value: 'lg', label: 'Grand' },
        { value: 'xl', label: 'Très grand' },
      ],
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'showDivider',
      label: 'Afficher un séparateur en bas',
      type: 'switch',
      defaultValue: false,
      showWhen: { field: 'enabled', value: true },
    },
  ],
}
