import type { ThemeSectionDef } from '../../../_types'

export const customGallerySection: ThemeSectionDef = {
  id: 'gallery',
  label: 'Galerie d\'images',
  description: 'Galerie d\'images dynamique ou personnalisée',
  fields: [
    {
      key: 'enabled',
      label: 'Activer cette section',
      type: 'switch',
      defaultValue: false,
    },
    {
      key: 'source',
      label: 'Source des images',
      type: 'select',
      defaultValue: 'restaurant',
      options: [
        { value: 'restaurant', label: 'Galerie du restaurant (dynamique)' },
        { value: 'custom', label: 'Images personnalisées' },
      ],
      description: 'Choisissez entre la galerie de votre identité ou des images uploadées manuellement',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'customImages',
      label: 'Images personnalisées',
      type: 'gallery',
      description: 'Uploadez vos propres images pour cette galerie',
      showWhen: { field: 'source', value: 'custom' },
    },
    {
      key: 'title',
      label: 'Titre',
      type: 'text',
      placeholder: 'Notre galerie',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'subtitle',
      label: 'Sous-titre',
      type: 'text',
      placeholder: 'Découvrez nos images',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'columns',
      label: 'Colonnes (desktop)',
      type: 'select',
      defaultValue: '3',
      options: [
        { value: '2', label: '2 colonnes' },
        { value: '3', label: '3 colonnes' },
        { value: '4', label: '4 colonnes' },
      ],
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'gap',
      label: 'Espacement entre images',
      type: 'select',
      defaultValue: 'md',
      options: [
        { value: 'sm', label: 'Petit' },
        { value: 'md', label: 'Moyen' },
        { value: 'lg', label: 'Grand' },
      ],
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'displayMode',
      label: 'Affichage des images',
      type: 'select',
      defaultValue: 'cover',
      options: [
        { value: 'original', label: 'Taille originale (masonry)' },
        { value: 'cover', label: 'Recadrées (grille uniforme)' },
      ],
      description: 'Taille originale conserve les proportions, recadrées remplit chaque cellule',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'aspectRatio',
      label: 'Ratio des images (mode recadré)',
      type: 'select',
      defaultValue: 'square',
      options: [
        { value: 'square', label: 'Carré (1:1)' },
        { value: 'video', label: 'Paysage (16:9)' },
        { value: 'portrait', label: 'Portrait (3:4)' },
      ],
      showWhen: { field: 'displayMode', value: 'cover' },
    },
    {
      key: 'enableViewer',
      label: 'Ouvrir les images en plein écran',
      type: 'switch',
      defaultValue: true,
      description: 'Permet de cliquer sur une image pour la voir en grand avec navigation',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'imageRounded',
      label: 'Arrondi des images',
      type: 'select',
      defaultValue: 'lg',
      options: [
        { value: 'none', label: 'Aucun' },
        { value: 'md', label: 'Léger' },
        { value: 'lg', label: 'Moyen' },
        { value: 'xl', label: 'Fort' },
      ],
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'bgColor',
      label: 'Couleur de fond',
      type: 'color',
      description: 'Laissez vide pour un fond transparent',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'paddingY',
      label: 'Espacement vertical',
      type: 'select',
      defaultValue: 'lg',
      options: [
        { value: 'sm', label: 'Petit' },
        { value: 'md', label: 'Moyen' },
        { value: 'lg', label: 'Grand' },
        { value: 'xl', label: 'Très grand' },
      ],
      showWhen: { field: 'enabled', value: true },
    },
  ],
}
