import type { ThemeSectionDef } from '../../../_types'

export const headerSection: ThemeSectionDef = {
  id: 'header',
  label: 'En-tête suivi',
  description: 'Bannière héro avec statut de la commande',
  fields: [
    {
      key: 'enabled',
      label: 'Activer la section',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'separatorNavigation',
      label: 'Navigation',
      type: 'separator',
    },
    {
      key: 'showBackButton',
      label: 'Afficher le bouton retour',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'backButtonText',
      label: 'Texte du bouton retour',
      type: 'text',
      placeholder: 'Menu',
      defaultValue: 'Menu',
      showWhen: { field: 'showBackButton', value: true },
    },
    {
      key: 'showRefreshButton',
      label: 'Afficher le bouton actualiser',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorInfo',
      label: 'Informations',
      type: 'separator',
    },
    {
      key: 'showEstimatedTime',
      label: 'Afficher le temps estimé',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'showOrderNumber',
      label: 'Afficher le numéro de commande',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'showCopyButton',
      label: 'Bouton copier le numéro',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'showOrderNumber', value: true },
    },
    {
      key: 'separatorBackground',
      label: 'Arrière-plan',
      type: 'separator',
    },
    {
      key: 'bgType',
      label: 'Type de fond',
      type: 'select',
      defaultValue: 'image',
      options: [
        { value: 'image', label: 'Image' },
        { value: 'gradient', label: 'Dégradé' },
        { value: 'none', label: 'Aucun (couleur de fond)' },
      ],
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'bgImage',
      label: 'Image de fond',
      type: 'image',
      showWhen: { field: 'bgType', value: 'image' },
    },
    {
      key: 'overlayOpacity',
      label: 'Opacité de l\'overlay',
      type: 'slider',
      min: 0,
      max: 100,
      step: 5,
      defaultValue: 60,
      showWhen: { field: 'bgType', value: 'image' },
    },
    {
      key: 'gradientFrom',
      label: 'Couleur de départ',
      type: 'color',
      showWhen: { field: 'bgType', value: 'gradient' },
    },
    {
      key: 'gradientTo',
      label: 'Couleur d\'arrivée',
      type: 'color',
      showWhen: { field: 'bgType', value: 'gradient' },
    },
    {
      key: 'minHeight',
      label: 'Hauteur minimale',
      type: 'select',
      defaultValue: '40vh',
      options: [
        { value: '30vh', label: 'Petite (30vh)' },
        { value: '40vh', label: 'Moyenne (40vh)' },
        { value: '50vh', label: 'Grande (50vh)' },
      ],
      showWhen: { field: 'enabled', value: true },
    },
  ],
}
