-- AlterTable
ALTER TABLE "RestaurantTheme" ADD COLUMN     "aboutText" TEXT,
ADD COLUMN     "aboutTitle" TEXT,
ADD COLUMN     "announcementActive" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "announcementBgColor" TEXT,
ADD COLUMN     "announcementText" TEXT,
ADD COLUMN     "buttonSize" TEXT NOT NULL DEFAULT 'md',
ADD COLUMN     "buttonStyle" TEXT NOT NULL DEFAULT 'rounded',
ADD COLUMN     "footerText" TEXT,
ADD COLUMN     "heroCtaText" TEXT DEFAULT 'Voir le menu',
ADD COLUMN     "heroOverlayOpacity" INTEGER NOT NULL DEFAULT 40,
ADD COLUMN     "heroStyle" TEXT NOT NULL DEFAULT 'banner',
ADD COLUMN     "heroSubtitle" TEXT,
ADD COLUMN     "heroTitle" TEXT,
ADD COLUMN     "logoPosition" TEXT NOT NULL DEFAULT 'left',
ADD COLUMN     "menuStyle" TEXT NOT NULL DEFAULT 'grid',
ADD COLUMN     "productCardStyle" TEXT NOT NULL DEFAULT 'standard',
ADD COLUMN     "showAllergens" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showCuisineTypes" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showPrepTime" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showProductImages" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showRatings" BOOLEAN NOT NULL DEFAULT true;
