import type { ThemeSectionDef } from '../../../_types'

export const cartDrawerSection: ThemeSectionDef = {
  id: 'cart-drawer',
  label: 'Panier',
  description: 'Configuration du panier latéral',
  fields: [
    {
      key: 'cartType',
      label: 'Type de panier',
      type: 'select',
      defaultValue: 'drawer',
      options: [
        { value: 'drawer', label: 'Panneau latéral' },
        { value: 'modal', label: 'Modal centré' },
        { value: 'mini', label: 'Mini panier (dropdown)' },
      ],
    },
    { key: 'separator1', label: 'Position et taille', type: 'separator' },
    {
      key: 'drawerPosition',
      label: 'Position du panneau',
      type: 'select',
      defaultValue: 'right',
      options: [
        { value: 'left', label: 'Gauche' },
        { value: 'right', label: 'Droite' },
      ],
      showWhen: { field: 'cartType', value: 'drawer' },
    },
    {
      key: 'drawerWidth',
      label: 'Largeur du panneau',
      type: 'select',
      defaultValue: 'md',
      options: [
        { value: 'sm', label: 'Étroit (320px)' },
        { value: 'md', label: 'Normal (400px)' },
        { value: 'lg', label: 'Large (480px)' },
      ],
      showWhen: { field: 'cartType', value: 'drawer' },
    },
    { key: 'separator2', label: 'Affichage des articles', type: 'separator' },
    {
      key: 'itemLayout',
      label: 'Style des articles',
      type: 'select',
      defaultValue: 'detailed',
      options: [
        { value: 'detailed', label: 'Détaillé (avec images)' },
        { value: 'compact', label: 'Compact (sans images)' },
        { value: 'minimal', label: 'Minimal (liste simple)' },
      ],
    },
    {
      key: 'showItemImages',
      label: 'Afficher les images',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'itemLayout', value: 'detailed' },
    },
    {
      key: 'imageSize',
      label: 'Taille des images',
      type: 'select',
      defaultValue: 'md',
      options: [
        { value: 'sm', label: 'Petite' },
        { value: 'md', label: 'Moyenne' },
        { value: 'lg', label: 'Grande' },
      ],
      showWhen: { field: 'showItemImages', value: true },
    },
    {
      key: 'showVariants',
      label: 'Afficher les variantes',
      type: 'switch',
      defaultValue: true,
      description: 'Ex: Taille M, Sauce piquante',
    },
    {
      key: 'showModifiers',
      label: 'Afficher les suppléments',
      type: 'switch',
      defaultValue: true,
      description: 'Ex: Extra fromage, Sans oignon',
    },
    {
      key: 'showUnitPrice',
      label: 'Afficher le prix unitaire',
      type: 'switch',
      defaultValue: false,
      description: 'Affiche le prix par unité quand quantité > 1',
    },
    { key: 'separator3', label: 'Contrôles', type: 'separator' },
    {
      key: 'quantityControlStyle',
      label: 'Style des contrôles de quantité',
      type: 'select',
      defaultValue: 'inline',
      options: [
        { value: 'inline', label: 'En ligne (- 1 +)' },
        { value: 'stepper', label: 'Stepper vertical' },
        { value: 'input', label: 'Champ de saisie' },
      ],
    },
    {
      key: 'allowRemoveFromCart',
      label: 'Permettre la suppression',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'showClearCartButton',
      label: 'Bouton "Vider le panier"',
      type: 'switch',
      defaultValue: true,
    },
    { key: 'separator4', label: 'Pied du panier', type: 'separator' },
    {
      key: 'showSubtotal',
      label: 'Afficher le sous-total',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'showItemCount',
      label: 'Afficher le nombre d\'articles',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'checkoutButtonText',
      label: 'Texte du bouton de commande',
      type: 'text',
      defaultValue: 'Commander',
      placeholder: 'Commander',
    },
    {
      key: 'showCheckoutButtonPrice',
      label: 'Afficher le prix dans le bouton',
      type: 'switch',
      defaultValue: true,
    },
    { key: 'separator5', label: 'Panier vide', type: 'separator' },
    {
      key: 'emptyCartTitle',
      label: 'Titre panier vide',
      type: 'text',
      defaultValue: 'Votre panier est vide',
      placeholder: 'Votre panier est vide',
    },
    {
      key: 'emptyCartMessage',
      label: 'Message panier vide',
      type: 'text',
      defaultValue: 'Ajoutez des articles depuis le menu',
      placeholder: 'Ajoutez des articles depuis le menu',
    },
    {
      key: 'showContinueShoppingButton',
      label: 'Bouton "Continuer mes achats"',
      type: 'switch',
      defaultValue: false,
    },
    { key: 'separator6', label: 'Animations', type: 'separator' },
    {
      key: 'enableAnimations',
      label: 'Activer les animations',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'animationSpeed',
      label: 'Vitesse des animations',
      type: 'select',
      defaultValue: 'normal',
      options: [
        { value: 'fast', label: 'Rapide' },
        { value: 'normal', label: 'Normal' },
        { value: 'slow', label: 'Lent' },
      ],
      showWhen: { field: 'enableAnimations', value: true },
    },
    {
      key: 'showBackdrop',
      label: 'Fond assombri',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'backdropBlur',
      label: 'Effet de flou sur le fond',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'showBackdrop', value: true },
    },
    {
      key: 'closeOnBackdropClick',
      label: 'Fermer en cliquant sur le fond',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'showBackdrop', value: true },
    },
  ],
}
