import type { ThemeSectionDef } from '../../../_types'

export const locationsSection: ThemeSectionDef = {
  id: 'locations',
  label: 'Emplacements & Contact',
  description: 'Section avec horaires, contact, bouton réservation et cartes Google Maps',
  syncFromPage: 'home',
  fields: [
    {
      key: 'enabled',
      label: 'Activer cette section',
      type: 'switch',
      defaultValue: false,
      description: 'Désactivée par défaut, activez pour afficher les emplacements',
    },
    {
      key: 'separatorData',
      label: 'Source des données',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'dataSource',
      label: 'Source des données',
      type: 'select',
      options: [
        { value: 'manual', label: 'Saisie manuelle' },
        { value: 'dynamic', label: 'Données du restaurant (automatique)' },
      ],
      defaultValue: 'manual',
      description: 'Utiliser les données du restaurant (horaires, adresse, contact) ou saisir manuellement',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorAppearance',
      label: 'Apparence',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'backgroundColor',
      label: 'Couleur de fond',
      type: 'color',
      defaultValue: '#0a0c10',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorHours',
      label: 'Horaires d\'ouverture',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'openingHoursTitle',
      label: 'Titre',
      type: 'text',
      placeholder: 'Horaires',
      defaultValue: 'Horaires',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'openingHoursLine1',
      label: 'Ligne 1',
      type: 'text',
      placeholder: 'Dim–Jeu: 12h – 22h',
      defaultValue: 'Dim–Jeu: 12h – 22h',
      showWhen: { field: 'dataSource', value: 'manual' },
    },
    {
      key: 'openingHoursLine2',
      label: 'Ligne 2',
      type: 'text',
      placeholder: 'Ven: Fermé',
      defaultValue: 'Ven: Fermé',
      showWhen: { field: 'dataSource', value: 'manual' },
    },
    {
      key: 'openingHoursLine3',
      label: 'Ligne 3',
      type: 'text',
      placeholder: 'Sam: 13h – 22h',
      defaultValue: 'Sam: 13h – 22h',
      showWhen: { field: 'dataSource', value: 'manual' },
    },
    {
      key: 'separatorLocation',
      label: 'Localisation',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'locationTitle',
      label: 'Titre',
      type: 'text',
      placeholder: 'Adresse',
      defaultValue: 'Adresse',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'locationLine1',
      label: 'Ligne 1',
      type: 'text',
      placeholder: 'Banani',
      defaultValue: 'Banani',
      showWhen: { field: 'dataSource', value: 'manual' },
    },
    {
      key: 'locationLine2',
      label: 'Ligne 2',
      type: 'text',
      placeholder: 'Dhanmondi',
      defaultValue: 'Dhanmondi',
      showWhen: { field: 'dataSource', value: 'manual' },
    },
    {
      key: 'locationLine3',
      label: 'Ligne 3',
      type: 'text',
      placeholder: 'Mirpur area',
      defaultValue: 'Mirpur area',
      showWhen: { field: 'dataSource', value: 'manual' },
    },
    {
      key: 'separatorContact',
      label: 'Contact rapide',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'contactTitle',
      label: 'Titre',
      type: 'text',
      placeholder: 'Contact',
      defaultValue: 'Contact',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'contactPhone',
      label: 'Téléphone',
      type: 'text',
      placeholder: '+880 01234-567890',
      defaultValue: '+880 01234-567890',
      showWhen: { field: 'dataSource', value: 'manual' },
    },
    {
      key: 'contactEmail',
      label: 'Email',
      type: 'text',
      placeholder: 'feasto@gmail.com',
      defaultValue: 'feasto@gmail.com',
      showWhen: { field: 'dataSource', value: 'manual' },
    },
    {
      key: 'separatorButton',
      label: 'Bouton d\'action',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'showActionButton',
      label: 'Afficher le bouton',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'actionButtonText',
      label: 'Texte du bouton',
      type: 'text',
      placeholder: 'Commander',
      defaultValue: 'Commander',
      showWhen: { field: 'showActionButton', value: true },
    },
    {
      key: 'actionButtonUrl',
      label: 'URL du bouton',
      type: 'text',
      placeholder: 'https://...',
      defaultValue: '#',
      description: 'Lien vers la page souhaitée',
      showWhen: { field: 'showActionButton', value: true },
    },
    {
      key: 'separatorLocation1',
      label: 'Carte 1 (principale)',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'location1Enabled',
      label: 'Afficher la carte 1',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'location1Title',
      label: 'Titre de l\'emplacement',
      type: 'text',
      placeholder: 'Hungerford Street, CA',
      defaultValue: 'Hungerford Street, CA',
      showWhen: { field: 'location1Enabled', value: true },
    },
    {
      key: 'location1MapEmbed',
      label: 'URL Google Maps Embed',
      type: 'text',
      placeholder: 'https://www.google.com/maps/embed?pb=...',
      defaultValue: '',
      description: 'Copiez l\'URL depuis Google Maps > Partager > Intégrer une carte',
      showWhen: { field: 'location1Enabled', value: true },
    },
    {
      key: 'location1MapUrl',
      label: 'Lien vers Google Maps',
      type: 'text',
      placeholder: 'https://maps.google.com/...',
      defaultValue: '#',
      description: 'Lien pour ouvrir la carte dans Google Maps',
      showWhen: { field: 'location1Enabled', value: true },
    },
    {
      key: 'separatorLocation2',
      label: 'Carte 2 (optionnelle)',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'location2Enabled',
      label: 'Afficher la carte 2',
      type: 'switch',
      defaultValue: false,
      description: 'Activez pour afficher un second emplacement',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'location2Title',
      label: 'Titre de l\'emplacement',
      type: 'text',
      placeholder: '2042 High Street, Oakland USA',
      defaultValue: '2042 High Street, Oakland USA',
      showWhen: { field: 'location2Enabled', value: true },
    },
    {
      key: 'location2MapEmbed',
      label: 'URL Google Maps Embed',
      type: 'text',
      placeholder: 'https://www.google.com/maps/embed?pb=...',
      defaultValue: '',
      description: 'Copiez l\'URL depuis Google Maps > Partager > Intégrer une carte',
      showWhen: { field: 'location2Enabled', value: true },
    },
    {
      key: 'location2MapUrl',
      label: 'Lien vers Google Maps',
      type: 'text',
      placeholder: 'https://maps.google.com/...',
      defaultValue: '#',
      description: 'Lien pour ouvrir la carte dans Google Maps',
      showWhen: { field: 'location2Enabled', value: true },
    },
    {
      key: 'separatorTexts',
      label: 'Textes',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'viewMapText',
      label: 'Texte "Voir sur la carte"',
      type: 'text',
      placeholder: 'Voir sur la carte',
      defaultValue: 'Voir sur la carte',
      showWhen: { field: 'enabled', value: true },
    },
  ],
}
