import type { ThemeSectionDef } from '../../../_types'

export const cartDrawerSection: ThemeSectionDef = {
  id: 'cart-drawer',
  label: 'Panier',
  description: 'Configuration du panier et de son affichage',
  fields: [
    {
      key: 'separatorType',
      label: 'Type de panier',
      type: 'separator',
    },
    {
      key: 'cartType',
      label: 'Style du panier',
      type: 'select',
      defaultValue: 'drawer',
      options: [
        { value: 'drawer', label: 'Panneau latéral (Drawer)' },
        { value: 'modal', label: 'Fenêtre modale (Modal)' },
        { value: 'mini', label: 'Mini panier (Dropdown)' },
      ],
      description: 'Comment le panier s\'affiche quand on clique sur l\'icône',
    },
    {
      key: 'drawerPosition',
      label: 'Position du panneau',
      type: 'select',
      defaultValue: 'right',
      options: [
        { value: 'right', label: 'À droite' },
        { value: 'left', label: 'À gauche' },
      ],
      showWhen: { field: 'cartType', value: 'drawer' },
    },
    {
      key: 'drawerWidth',
      label: 'Largeur du panneau',
      type: 'select',
      defaultValue: 'md',
      options: [
        { value: 'sm', label: 'Étroit (320px)' },
        { value: 'md', label: 'Normal (400px)' },
        { value: 'lg', label: 'Large (480px)' },
      ],
      showWhen: { field: 'cartType', value: 'drawer' },
    },
    {
      key: 'separatorDisplay',
      label: 'Affichage des articles',
      type: 'separator',
    },
    {
      key: 'itemLayout',
      label: 'Disposition des articles',
      type: 'select',
      defaultValue: 'detailed',
      options: [
        { value: 'detailed', label: 'Détaillé (avec images)' },
        { value: 'compact', label: 'Compact (sans images)' },
        { value: 'minimal', label: 'Minimal (liste simple)' },
      ],
    },
    {
      key: 'showItemImages',
      label: 'Afficher les images des produits',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'itemLayout', value: 'detailed' },
    },
    {
      key: 'imageSize',
      label: 'Taille des images',
      type: 'select',
      defaultValue: 'md',
      options: [
        { value: 'sm', label: 'Petite (48px)' },
        { value: 'md', label: 'Moyenne (64px)' },
        { value: 'lg', label: 'Grande (80px)' },
      ],
      showWhen: { field: 'showItemImages', value: true },
    },
    {
      key: 'showVariants',
      label: 'Afficher les variantes',
      type: 'switch',
      defaultValue: true,
      description: 'Ex: Taille M, Sauce piquante',
    },
    {
      key: 'showModifiers',
      label: 'Afficher les suppléments',
      type: 'switch',
      defaultValue: true,
      description: 'Ex: Extra fromage, Sans oignons',
    },
    {
      key: 'showUnitPrice',
      label: 'Afficher le prix unitaire',
      type: 'switch',
      defaultValue: false,
      description: 'En plus du prix total de la ligne',
    },
    {
      key: 'separatorQuantity',
      label: 'Contrôle des quantités',
      type: 'separator',
    },
    {
      key: 'quantityControlStyle',
      label: 'Style des boutons quantité',
      type: 'select',
      defaultValue: 'inline',
      options: [
        { value: 'inline', label: 'En ligne (- 1 +)' },
        { value: 'stepper', label: 'Stepper vertical' },
        { value: 'input', label: 'Champ de saisie' },
      ],
    },
    {
      key: 'allowRemoveFromCart',
      label: 'Permettre la suppression d\'articles',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'showClearCartButton',
      label: 'Bouton "Vider le panier"',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'separatorFooter',
      label: 'Pied du panier',
      type: 'separator',
    },
    {
      key: 'showSubtotal',
      label: 'Afficher le sous-total',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'showEstimatedFees',
      label: 'Afficher les frais estimés',
      type: 'switch',
      defaultValue: false,
      description: 'Frais de livraison, taxes estimées',
    },
    {
      key: 'showItemCount',
      label: 'Afficher le nombre d\'articles',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'checkoutButtonText',
      label: 'Texte du bouton commander',
      type: 'text',
      defaultValue: 'Commander',
      description: 'Le prix sera ajouté automatiquement',
    },
    {
      key: 'showCheckoutButtonPrice',
      label: 'Afficher le prix dans le bouton',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'separatorEmpty',
      label: 'Panier vide',
      type: 'separator',
    },
    {
      key: 'emptyCartTitle',
      label: 'Titre panier vide',
      type: 'text',
      defaultValue: 'Votre panier est vide',
    },
    {
      key: 'emptyCartMessage',
      label: 'Message panier vide',
      type: 'text',
      defaultValue: 'Ajoutez des articles depuis le menu',
    },
    {
      key: 'showContinueShoppingButton',
      label: 'Bouton "Continuer mes achats"',
      type: 'switch',
      defaultValue: false,
    },
    {
      key: 'separatorAnimation',
      label: 'Animations',
      type: 'separator',
    },
    {
      key: 'enableAnimations',
      label: 'Activer les animations',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'animationSpeed',
      label: 'Vitesse des animations',
      type: 'select',
      defaultValue: 'normal',
      options: [
        { value: 'fast', label: 'Rapide (200ms)' },
        { value: 'normal', label: 'Normal (300ms)' },
        { value: 'slow', label: 'Lent (500ms)' },
      ],
      showWhen: { field: 'enableAnimations', value: true },
    },
    {
      key: 'showBackdrop',
      label: 'Afficher le fond assombri',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'backdropBlur',
      label: 'Effet de flou sur le fond',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'showBackdrop', value: true },
    },
    {
      key: 'closeOnBackdropClick',
      label: 'Fermer en cliquant sur le fond',
      type: 'switch',
      defaultValue: true,
    },
  ],
}
