import type { ThemeSectionDef } from '../../../_types'

export const heroSection: ThemeSectionDef = {
  id: 'hero',
  label: 'En-tête de page',
  description: 'Bannière principale avec titre et image de fond',
  fields: [
    {
      key: 'enabled',
      label: 'Activer cette section',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'separatorContent',
      label: 'Contenu',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'label',
      label: 'Label',
      type: 'text',
      placeholder: 'À propos',
      defaultValue: 'À propos',
      description: 'Petit texte au-dessus du titre',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'title',
      label: 'Titre',
      type: 'text',
      placeholder: 'Notre histoire',
      description: 'Laissez vide pour utiliser "Notre histoire"',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'subtitle',
      label: 'Sous-titre',
      type: 'textarea',
      placeholder: 'Découvrez qui nous sommes...',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorAppearance',
      label: 'Apparence',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'backgroundImage',
      label: 'Image de fond',
      type: 'image',
      description: 'Laissez vide pour utiliser la cover du restaurant',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'overlayOpacity',
      label: 'Opacité du fond',
      type: 'slider',
      min: 0,
      max: 100,
      step: 5,
      defaultValue: 60,
      description: 'Assombrir l\'image de fond',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'blurAmount',
      label: 'Flou du fond',
      type: 'slider',
      min: 0,
      max: 20,
      step: 1,
      defaultValue: 8,
      description: 'Effet de flou sur l\'image',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'showScrollDown',
      label: 'Afficher le bouton de défilement',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'enabled', value: true },
    },
  ],
}
