import type { ThemeSectionDef } from '../../../_types'

export const storySection: ThemeSectionDef = {
  id: 'story',
  label: 'Notre histoire',
  description: 'Section avec texte, image principale et statistiques',
  fields: [
    {
      key: 'enabled',
      label: 'Activer cette section',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'separatorAppearance',
      label: 'Apparence',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'backgroundColor',
      label: 'Couleur de fond',
      type: 'color',
      defaultValue: '#0a0c10',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'cardColor',
      label: 'Couleur des cartes',
      type: 'color',
      defaultValue: '#0e1416',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'cardRadius',
      label: 'Arrondi des cartes',
      type: 'select',
      options: [
        { value: 'none', label: 'Aucun' },
        { value: 'sm', label: 'Léger' },
        { value: 'md', label: 'Moyen' },
        { value: 'lg', label: 'Arrondi' },
        { value: 'xl', label: 'Très arrondi' },
        { value: '2xl', label: 'Extra arrondi' },
      ],
      defaultValue: 'none',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorContent',
      label: 'Contenu principal',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'titlePart1',
      label: 'Titre (partie 1)',
      type: 'text',
      placeholder: 'A Cozy Place Built for',
      defaultValue: 'A Cozy Place Built for',
      description: 'Première partie du titre (couleur blanche)',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'titlePart2',
      label: 'Titre (partie 2 - accentuée)',
      type: 'text',
      placeholder: 'Good Food & Good Moments',
      defaultValue: 'Good Food & Good Moments',
      description: 'Partie accentuée du titre (couleur primaire)',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'description',
      label: 'Description',
      type: 'textarea',
      placeholder: 'Nous avons créé ce restaurant avec une conviction simple...',
      defaultValue: 'Nous avons créé ce restaurant avec une conviction simple — la bonne cuisine n\'a pas besoin d\'être compliquée, et une atmosphère chaleureuse rend toujours un repas meilleur.',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorButton',
      label: 'Bouton',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'showButton',
      label: 'Afficher le bouton',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'buttonText',
      label: 'Texte du bouton',
      type: 'text',
      placeholder: 'Réserver une table',
      defaultValue: 'Réserver une table',
      showWhen: { field: 'showButton', value: true },
    },
    {
      key: 'buttonLink',
      label: 'Lien du bouton',
      type: 'text',
      placeholder: 'https://...',
      defaultValue: '#',
      showWhen: { field: 'showButton', value: true },
    },
    {
      key: 'buttonIcon',
      label: 'Icône du bouton',
      type: 'icon',
      showWhen: { field: 'showButton', value: true },
    },
    {
      key: 'separatorBadges',
      label: 'Badges de notation',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'showBadges',
      label: 'Afficher les badges',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'badge1Text',
      label: 'Badge 1',
      type: 'text',
      placeholder: 'Top Restaurant 23',
      defaultValue: 'Top Restaurant 23',
      showWhen: { field: 'showBadges', value: true },
    },
    {
      key: 'badge2Text',
      label: 'Badge 2',
      type: 'text',
      placeholder: 'Top Restaurant 24',
      defaultValue: 'Top Restaurant 24',
      showWhen: { field: 'showBadges', value: true },
    },
    {
      key: 'separatorImage',
      label: 'Image principale',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'mainImage',
      label: 'Image',
      type: 'image',
      description: 'Image centrale de la section (format portrait recommandé)',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorStats',
      label: 'Statistiques',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'stat1Icon',
      label: 'Icône statistique 1',
      type: 'icon',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'stat1Number',
      label: 'Chiffre statistique 1',
      type: 'text',
      placeholder: '25,000+',
      defaultValue: '25,000+',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'stat1Label',
      label: 'Label statistique 1',
      type: 'text',
      placeholder: 'Clients satisfaits chaque jour',
      defaultValue: 'Clients satisfaits chaque jour',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'stat2Icon',
      label: 'Icône statistique 2',
      type: 'icon',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'stat2Number',
      label: 'Chiffre statistique 2',
      type: 'text',
      placeholder: '4.8',
      defaultValue: '4.8',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'stat2HasStar',
      label: 'Afficher étoile après le chiffre',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'stat2Label',
      label: 'Label statistique 2',
      type: 'text',
      placeholder: 'Où chaque repas est spécial',
      defaultValue: 'Où chaque repas est spécial',
      showWhen: { field: 'enabled', value: true },
    },
  ],
}
