import type { ThemeSectionDef } from '../../../_types'

export const teamSection: ThemeSectionDef = {
  id: 'team',
  label: 'Équipe',
  description: 'Section présentant les membres de l\'équipe',
  fields: [
    {
      key: 'enabled',
      label: 'Activer cette section',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'separatorAppearance',
      label: 'Apparence',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'backgroundColor',
      label: 'Couleur de fond',
      type: 'color',
      defaultValue: '#0a0c10',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'cardColor',
      label: 'Couleur des cartes',
      type: 'color',
      defaultValue: '#12161a',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'cardRadius',
      label: 'Arrondi des cartes',
      type: 'select',
      options: [
        { value: 'none', label: 'Aucun' },
        { value: 'sm', label: 'Léger' },
        { value: 'md', label: 'Moyen' },
        { value: 'lg', label: 'Arrondi' },
        { value: 'xl', label: 'Très arrondi' },
        { value: '2xl', label: 'Extra arrondi' },
      ],
      defaultValue: 'none',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorContent',
      label: 'Contenu',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'titlePart1',
      label: 'Titre (partie 1)',
      type: 'text',
      placeholder: 'The Dedicated Team',
      defaultValue: 'The Dedicated Team',
      description: 'Première partie du titre (couleur blanche)',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'titlePart2',
      label: 'Titre (partie 2 - soulignée)',
      type: 'text',
      placeholder: 'Behind Your Favorite Meals',
      defaultValue: 'Behind Your Favorite Meals',
      description: 'Partie soulignée du titre (couleur primaire)',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorData',
      label: 'Source des données',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'dataSource',
      label: 'Source des membres',
      type: 'select',
      options: [
        { value: 'manual', label: 'Ajout manuel' },
        { value: 'dynamic', label: 'Équipe du restaurant (automatique)' },
      ],
      defaultValue: 'manual',
      description: 'Choisir d\'où proviennent les membres de l\'équipe',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'visibleRoles',
      label: 'Rôles à afficher',
      type: 'multiselect',
      options: [
        { value: 'OWNER', label: 'OWNER' },
        { value: 'MANAGER', label: 'MANAGER' },
        { value: 'STAFF', label: 'STAFF' },
        { value: 'CASHIER', label: 'CASHIER' },
        { value: 'KITCHEN', label: 'KITCHEN' },
      ],
      defaultValue: ['OWNER', 'MANAGER', 'STAFF', 'CASHIER', 'KITCHEN'],
      showWhen: { field: 'dataSource', value: 'dynamic' },
    },
    {
      key: 'members',
      label: 'Membres de l\'équipe',
      type: 'array',
      itemLabel: 'Membre',
      defaultValue: [
        { id: '1', name: 'Brooklyn Simmons', position: 'Fish Chef', avatar: '', socialLink: '' },
        { id: '2', name: 'Guy Hawkins', position: 'Grill Chef', avatar: '', socialLink: '' },
        { id: '3', name: 'Jenny Wilson', position: 'Burger Chef', avatar: '', socialLink: '' },
      ],
      itemFields: [
        {
          key: 'name',
          label: 'Nom',
          type: 'text',
          placeholder: 'John Doe',
          defaultValue: '',
        },
        {
          key: 'position',
          label: 'Poste',
          type: 'text',
          placeholder: 'Chef cuisinier',
          defaultValue: '',
        },
        {
          key: 'avatar',
          label: 'Photo',
          type: 'image',
          defaultValue: '',
        },
        {
          key: 'socialLink',
          label: 'Lien social (Instagram, etc.)',
          type: 'text',
          placeholder: 'https://instagram.com/...',
          defaultValue: '',
        },
      ],
      showWhen: { field: 'dataSource', value: 'manual' },
    },
    {
      key: 'separatorDisplay',
      label: 'Affichage',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'displayMode',
      label: 'Mode d\'affichage',
      type: 'select',
      options: [
        { value: 'grid', label: 'Grille complète' },
        { value: 'carousel', label: 'Carrousel' },
      ],
      defaultValue: 'grid',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'columnsCount',
      label: 'Nombre de colonnes',
      type: 'select',
      options: [
        { value: '2', label: '2 colonnes' },
        { value: '3', label: '3 colonnes' },
        { value: '4', label: '4 colonnes' },
      ],
      defaultValue: '3',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'autoPlaySpeed',
      label: 'Vitesse du carrousel (secondes)',
      type: 'number',
      defaultValue: 5,
      min: 0,
      max: 20,
      description: '0 pour désactiver le défilement automatique',
      showWhen: { field: 'displayMode', value: 'carousel' },
    },
    {
      key: 'showSocialIcon',
      label: 'Afficher l\'icône sociale',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'enabled', value: true },
    },
  ],
}
