import type { ThemeSectionDef } from '../../../_types'

export const timelineSection: ThemeSectionDef = {
  id: 'timeline',
  label: 'Timeline',
  description: 'Section chronologique avec animation au scroll',
  fields: [
    {
      key: 'enabled',
      label: 'Activer cette section',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'separatorAppearance',
      label: 'Apparence',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'backgroundColor',
      label: 'Couleur de fond',
      type: 'color',
      defaultValue: '#0e1416',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'columnOrder',
      label: 'Ordre des colonnes',
      type: 'select',
      options: [
        { value: 'content-timeline', label: 'Contenu à gauche, Timeline à droite' },
        { value: 'timeline-content', label: 'Timeline à gauche, Contenu à droite' },
      ],
      defaultValue: 'content-timeline',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorContent',
      label: 'Contenu',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'titlePart1',
      label: 'Titre (partie 1)',
      type: 'text',
      placeholder: 'Crafting Warm Memories',
      defaultValue: 'Crafting Warm Memories',
      description: 'Première partie du titre (couleur blanche)',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'titlePart2',
      label: 'Titre (partie 2 - accentuée)',
      type: 'text',
      placeholder: 'Through Five Delicious Years',
      defaultValue: 'Through Five Delicious Years',
      description: 'Partie accentuée du titre (couleur primaire)',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'sideImage',
      label: 'Image latérale',
      type: 'image',
      description: 'Image verticale à côté du titre',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'imageRadius',
      label: 'Arrondi de l\'image',
      type: 'select',
      options: [
        { value: 'none', label: 'Aucun' },
        { value: 'sm', label: 'Léger' },
        { value: 'md', label: 'Moyen' },
        { value: 'lg', label: 'Arrondi' },
        { value: 'xl', label: 'Très arrondi' },
        { value: '2xl', label: 'Extra arrondi' },
      ],
      defaultValue: 'lg',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorTimeline',
      label: 'Éléments de la timeline',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'items',
      label: 'Éléments',
      type: 'array',
      itemLabel: 'Élément',
      defaultValue: [
        {
          marker: '2021',
          markerType: 'year',
          title: 'The Beginning',
          description: 'We started with a simple dream: to create a cozy place where people could enjoy fresh, honest food.',
        },
        {
          marker: '2022',
          markerType: 'year',
          title: 'Building Trust',
          description: 'Word spread, and more families, friends, and food lovers began visiting us.',
        },
        {
          marker: '2023',
          markerType: 'year',
          title: 'Growing Stronger',
          description: 'Our menu expanded with new favorites, and our team grew with dedicated members.',
        },
        {
          marker: '2024',
          markerType: 'year',
          title: 'Becoming a Community Favorite',
          description: 'We upgraded our space, added comfort elements, and focused on delivering even better experiences.',
        },
      ],
      itemFields: [
        {
          key: 'markerType',
          label: 'Type de marqueur',
          type: 'select',
          options: [
            { value: 'year', label: 'Année' },
            { value: 'text', label: 'Texte' },
            { value: 'icon', label: 'Icône' },
          ],
          defaultValue: 'year',
        },
        {
          key: 'marker',
          label: 'Marqueur',
          type: 'text',
          placeholder: '2021',
          defaultValue: '2021',
          description: 'Année, texte ou nom d\'icône selon le type',
        },
        {
          key: 'title',
          label: 'Titre',
          type: 'text',
          placeholder: 'The Beginning',
          defaultValue: '',
        },
        {
          key: 'description',
          label: 'Description',
          type: 'textarea',
          placeholder: 'Description de cette étape...',
          defaultValue: '',
        },
      ],
      showWhen: { field: 'enabled', value: true },
    },
  ],
}
