import type { ThemeSectionDef } from '../../../_types'

export const heroSection: ThemeSectionDef = {
  id: 'hero',
  label: 'Hero',
  description: 'Bannière principale avec titre, description, boutons et images',
  fields: [
    {
      key: 'enabled',
      label: 'Activer la section',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'separator1',
      label: 'Contenu',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'title',
      label: 'Titre principal',
      type: 'text',
      placeholder: 'Where Good Food Meets a Cozy, Family-Friendly Space',
      defaultValue: 'Where Good Food Meets a Cozy, Family-Friendly Space',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'subtitle',
      label: 'Sous-titre',
      type: 'textarea',
      placeholder: 'Découvrez une cuisine raffinée dans une ambiance chaleureuse...',
      defaultValue: 'Découvrez une cuisine raffinée dans une ambiance chaleureuse et conviviale.',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorGoogle',
      label: 'Badge Google',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'showGoogleBadge',
      label: 'Afficher le badge Google',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'googleRating',
      label: 'Note Google',
      type: 'text',
      placeholder: '4.9',
      defaultValue: '4.9',
      showWhen: { field: 'showGoogleBadge', value: true },
    },
    {
      key: 'separator2',
      label: 'Boutons',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'ctaText',
      label: 'Texte du bouton principal',
      type: 'text',
      placeholder: 'Voir le menu',
      defaultValue: 'Voir le menu',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'ctaIcon',
      label: 'Icône du bouton principal',
      type: 'icon',
      defaultValue: 'Menu',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'showSecondaryBtn',
      label: 'Afficher le bouton secondaire',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'secondaryBtnText',
      label: 'Texte du bouton secondaire',
      type: 'text',
      placeholder: 'Réserver une table',
      defaultValue: 'Réserver une table',
      showWhen: { field: 'showSecondaryBtn', value: true },
    },
    {
      key: 'secondaryBtnIcon',
      label: 'Icône du bouton secondaire',
      type: 'icon',
      defaultValue: 'CalendarDays',
      showWhen: { field: 'showSecondaryBtn', value: true },
    },
    {
      key: 'secondaryBtnLink',
      label: 'Lien du bouton secondaire',
      type: 'select',
      options: [
        { value: 'contact', label: 'Page Contact' },
        { value: 'menu', label: 'Page Menu' },
      ],
      defaultValue: 'contact',
      showWhen: { field: 'showSecondaryBtn', value: true },
    },
    {
      key: 'separator3',
      label: 'Images',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'mainImage',
      label: 'Image principale',
      type: 'image',
      description: 'Grande image affichée à droite du hero',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'floatingImage',
      label: 'Image flottante',
      type: 'image',
      description: 'Petite image ovale flottante à côté de l\'image principale',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'sideImages',
      label: 'Galerie d\'images',
      type: 'gallery',
      description: 'Images qui défilent automatiquement dans la colonne de droite',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'slideshowAnimation',
      label: 'Animation du diaporama',
      type: 'select',
      options: [
        { value: 'fade', label: 'Fondu' },
        { value: 'slide', label: 'Glissement' },
        { value: 'zoom', label: 'Zoom' },
      ],
      defaultValue: 'fade',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'slideshowInterval',
      label: 'Intervalle (secondes)',
      type: 'slider',
      min: 3,
      max: 15,
      step: 1,
      defaultValue: 5,
      description: 'Durée d\'affichage de chaque image',
      showWhen: { field: 'enabled', value: true },
    },
  ],
}
