import type { ThemeSectionDef } from '../../../_types'

export const qualityFoodSection: ThemeSectionDef = {
  id: 'qualityFood',
  label: 'Qualité & Atouts',
  description: 'Section avec titre, sous-titre et 4 icônes de points forts',
  fields: [
    {
      key: 'enabled',
      label: 'Activer la section',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'separatorAppearance',
      label: 'Apparence',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'backgroundColor',
      label: 'Couleur de fond',
      type: 'color',
      defaultValue: '#0e1416',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'iconShape',
      label: 'Forme des icônes',
      type: 'select',
      options: [
        { value: 'circle', label: 'Cercle' },
        { value: 'rounded', label: 'Carré arrondi' },
        { value: 'hexagon', label: 'Hexagone' },
      ],
      defaultValue: 'circle',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorIcon',
      label: 'Icône de séparation',
      type: 'icon',
      defaultValue: 'MoveRight',
      description: 'Icône affichée entre chaque point fort',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorContent',
      label: 'Contenu',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'titleLine1',
      label: 'Titre ligne 1',
      type: 'text',
      placeholder: 'Quality Food,',
      defaultValue: 'Quality Food,',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'titleLine2',
      label: 'Titre ligne 2 (italique)',
      type: 'text',
      placeholder: 'Comfort Every Time',
      defaultValue: 'Comfort Every Time',
      description: 'Affiché en italique avec la couleur principale',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'subtitle',
      label: 'Sous-titre',
      type: 'textarea',
      placeholder: 'Enjoy fresh, flavorful dishes...',
      defaultValue: 'Enjoy fresh, flavorful dishes in a warm atmosphere that feels just right for family dinners, friendly hangouts, and small celebrations.',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorFeature1',
      label: 'Point fort 1',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'feature1Icon',
      label: 'Icône',
      type: 'icon',
      defaultValue: 'ChefHat',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'feature1Label',
      label: 'Texte',
      type: 'text',
      placeholder: 'Talented chefs',
      defaultValue: 'Talented chefs',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorFeature2',
      label: 'Point fort 2',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'feature2Icon',
      label: 'Icône',
      type: 'icon',
      defaultValue: 'UtensilsCrossed',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'feature2Label',
      label: 'Texte',
      type: 'text',
      placeholder: 'Superb dishes',
      defaultValue: 'Superb dishes',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorFeature3',
      label: 'Point fort 3',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'feature3Icon',
      label: 'Icône',
      type: 'icon',
      defaultValue: 'Clock',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'feature3Label',
      label: 'Texte',
      type: 'text',
      placeholder: 'Amazing service',
      defaultValue: 'Amazing service',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorFeature4',
      label: 'Point fort 4',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'feature4Icon',
      label: 'Icône',
      type: 'icon',
      defaultValue: 'ConciergeBell',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'feature4Label',
      label: 'Texte',
      type: 'text',
      placeholder: 'Array of Meals',
      defaultValue: 'Array of Meals',
      showWhen: { field: 'enabled', value: true },
    },
  ],
}
