import type { ThemeSectionDef } from '../../../_types'

export const testimonialsSection: ThemeSectionDef = {
  id: 'testimonials',
  label: 'Témoignages clients',
  description: 'Carrousel de témoignages avec images de produits liés',
  fields: [
    {
      key: 'enabled',
      label: 'Activer cette section',
      type: 'switch',
      defaultValue: false,
      description: 'Désactivée par défaut, activez pour afficher les témoignages',
    },
    {
      key: 'separatorAppearance',
      label: 'Apparence',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'backgroundColor',
      label: 'Couleur de fond',
      type: 'color',
      defaultValue: '#0e1416',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorContent',
      label: 'Contenu',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'titleLine1',
      label: 'Titre ligne 1',
      type: 'text',
      placeholder: 'Loved by',
      defaultValue: 'Loved by',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'titleLine2',
      label: 'Titre ligne 2',
      type: 'text',
      placeholder: 'Food Lovers & Regular Guests',
      defaultValue: 'Food Lovers & Regular Guests',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'highlightWords',
      label: 'Mots à mettre en couleur',
      type: 'text',
      placeholder: 'Lovers,Regular',
      defaultValue: 'Lovers,Regular',
      description: 'Séparez les mots par des virgules',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorCarousel',
      label: 'Carrousel',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'visibleCount',
      label: 'Témoignages visibles',
      type: 'slider',
      min: 1,
      max: 3,
      step: 1,
      defaultValue: 2,
      description: 'Nombre de témoignages affichés simultanément',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'autoplay',
      label: 'Défilement automatique',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'autoplayDelay',
      label: 'Délai entre défilements (secondes)',
      type: 'slider',
      min: 3,
      max: 10,
      step: 1,
      defaultValue: 5,
      showWhen: { field: 'autoplay', value: true },
    },
    {
      key: 'equalHeight',
      label: 'Hauteur égale des cartes',
      type: 'switch',
      defaultValue: true,
      description: 'Toutes les cartes auront la même hauteur',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separatorTestimonials',
      label: 'Témoignages',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'testimonials',
      label: 'Liste des témoignages',
      type: 'testimonials-with-product',
      description: 'Ajoutez des témoignages avec un produit lié pour afficher son image',
      showWhen: { field: 'enabled', value: true },
    },
  ],
}
