import type { ThemeSectionDef } from '../../../_types'

export const twoColumnsSection: ThemeSectionDef = {
  id: 'twoColumns',
  label: 'Deux colonnes',
  description: 'Section texte et images en deux colonnes alternées',
  fields: [
    {
      key: 'enabled',
      label: 'Activer la section',
      type: 'switch',
      defaultValue: true,
    },
    {
      key: 'separatorAppearance',
      label: 'Apparence',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'backgroundColor',
      label: 'Couleur de fond',
      type: 'color',
      defaultValue: '#0C0C0C',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'imageRatio',
      label: 'Ratio des images',
      type: 'select',
      options: [
        { value: '4/5', label: 'Portrait (4:5)' },
        { value: '3/4', label: 'Portrait haut (3:4)' },
        { value: '1/1', label: 'Carré (1:1)' },
        { value: '4/3', label: 'Paysage (4:3)' },
        { value: '16/9', label: 'Cinéma (16:9)' },
      ],
      defaultValue: '4/5',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'imageRadius',
      label: 'Arrondi des images',
      type: 'select',
      options: [
        { value: 'none', label: 'Aucun' },
        { value: 'md', label: 'Léger' },
        { value: 'xl', label: 'Moyen' },
        { value: '2xl', label: 'Arrondi' },
        { value: '3xl', label: 'Très arrondi' },
      ],
      defaultValue: '2xl',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'separator1',
      label: 'Premier bloc',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'block1Title',
      label: 'Titre',
      type: 'text',
      placeholder: 'Notre histoire',
      description: 'Laissez vide pour utiliser le nom du restaurant',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'block1Text',
      label: 'Texte',
      type: 'textarea',
      placeholder: 'Décrivez votre restaurant, votre histoire...',
      description: 'Laissez vide pour utiliser la description du restaurant',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'block1Image',
      label: 'Image',
      type: 'image',
      description: 'Image principale du bloc. Laissez vide pour utiliser la cover du restaurant',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'showBlock1Btn',
      label: 'Afficher le bouton',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'block1BtnText',
      label: 'Texte du bouton',
      type: 'text',
      placeholder: 'En savoir plus',
      defaultValue: 'En savoir plus',
      showWhen: { field: 'showBlock1Btn', value: true },
    },
    {
      key: 'block1BtnIcon',
      label: 'Icône du bouton',
      type: 'icon',
      showWhen: { field: 'showBlock1Btn', value: true },
    },
    {
      key: 'block1BtnLink',
      label: 'Lien du bouton',
      type: 'select',
      options: [
        { value: 'contact', label: 'Page Contact' },
        { value: 'menu', label: 'Page Menu' },
      ],
      defaultValue: 'contact',
      showWhen: { field: 'showBlock1Btn', value: true },
    },
    {
      key: 'separator2',
      label: 'Deuxième bloc',
      type: 'separator',
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'showBlock2',
      label: 'Afficher le deuxième bloc',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'enabled', value: true },
    },
    {
      key: 'block2Title',
      label: 'Titre',
      type: 'text',
      placeholder: 'Notre passion',
      defaultValue: 'Notre passion',
      showWhen: { field: 'showBlock2', value: true },
    },
    {
      key: 'block2Text',
      label: 'Texte',
      type: 'textarea',
      placeholder: 'Décrivez ce qui vous rend unique...',
      defaultValue: 'Un menu personnalisé selon vos goûts et vos envies du moment.',
      showWhen: { field: 'showBlock2', value: true },
    },
    {
      key: 'block2Image',
      label: 'Image',
      type: 'image',
      description: 'Image principale du bloc',
      showWhen: { field: 'showBlock2', value: true },
    },
    {
      key: 'showBlock2Btn',
      label: 'Afficher le bouton',
      type: 'switch',
      defaultValue: true,
      showWhen: { field: 'showBlock2', value: true },
    },
    {
      key: 'block2BtnText',
      label: 'Texte du bouton',
      type: 'text',
      placeholder: 'Voir le menu',
      defaultValue: 'Voir le menu',
      showWhen: { field: 'showBlock2Btn', value: true },
    },
    {
      key: 'block2BtnIcon',
      label: 'Icône du bouton',
      type: 'icon',
      showWhen: { field: 'showBlock2Btn', value: true },
    },
    {
      key: 'block2BtnLink',
      label: 'Lien du bouton',
      type: 'select',
      options: [
        { value: 'menu', label: 'Page Menu' },
        { value: 'contact', label: 'Page Contact' },
      ],
      defaultValue: 'menu',
      showWhen: { field: 'showBlock2Btn', value: true },
    },
  ],
}
